#ifndef state_machine_h
#define state_machine_h

enum state {
  BEGIN,
  WAIT_FOR_CARD,   
  COLLECT_CARD_DATA,
  SAY_HELLO,
  NOT_THE_GOOD_DAY,
  CAPTURE_USER_ENTRIES,
  GOOD_CODE,
  WRONG_CODE,
  WAIT_FOR_CARD_REMOVE,
  DISPLAY_DISTRIBUTION,
  DISTRIBUTION,
  SAY_GOODBYE,
  WAIT,
  UNEXPECTED_CARD_REMOVE
};

#endif
